name: Docker Lab CI

on:
  push:
    branches:
      - main

jobs:
  docker-validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Docker Compose
        run: docker compose config

      - name: List files
        run: ls -la
